from .common import (
    is_admin,
    is_doctor,
    is_patient,
)

from .public import (
    home_view,
    adminclick_view,
    doctorclick_view,
    patientclick_view,
    admin_signup_view,
    doctor_signup_view,
    patient_signup_view,
    afterlogin_view,
    aboutus_view,
    contactus_view,
)

from .admin import (
    admin_dashboard_view,
    admin_doctor_view,
    admin_view_doctor_view,
    delete_doctor_from_hospital_view,
    update_doctor_view,
    admin_add_doctor_view,
    admin_approve_doctor_view,
    approve_doctor_view,
    reject_doctor_view,
    admin_view_doctor_specialisation_view,
    admin_patient_view,
    admin_view_patient_view,
    delete_patient_from_hospital_view,
    update_patient_view,
    admin_add_patient_view,
    admin_approve_patient_view,
    approve_patient_view,
    reject_patient_view,
    admin_discharge_patient_view,
    discharge_patient_view,
    render_to_pdf,
    download_pdf_view,
    admin_appointment_view,
    admin_view_appointment_view,
    admin_add_appointment_view,
    admin_approve_appointment_view,
    approve_appointment_view,
    reject_appointment_view,
    admin_activity_view,
    admin_add_activity_view,
    admin_view_activity_view,
    update_activity_view,
    delete_activity_view,
    admin_volunteer_view,
    admin_add_volunteer_view,
    approve_volunteer_view,
    reject_volunteer_view,
    admin_station_view,
    admin_add_station_view,
    update_station_view,
    delete_station_view,
    admin_medical_records_view,
    admin_view_record_view,
)

from .doctor import (
    doctor_dashboard_view,
    doctor_patient_view,
    doctor_qrcode_view,
    doctor_view_patient_view,
    search_view,
    doctor_view_discharge_patient_view,
    doctor_appointment_view,
    doctor_view_appointment_view,
    doctor_delete_appointment_view,
    delete_appointment_view,
    doctor_records_view,
    doctor_create_record_view,
    doctor_update_record_view,
)

from .patient import (
    patient_dashboard_view,
    patient_appointment_view,
    patient_book_appointment_view,
    patient_view_doctor_view,
    search_doctor_view,
    patient_view_appointment_view,
    patient_discharge_view,
    patient_records_view,
    patient_view_record_view,
)
