# Generated by Django 4.2.29 on 2026-03-21 08:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='活动名称')),
                ('location', models.CharField(max_length=100, verbose_name='活动地点')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('description', models.TextField(blank=True, verbose_name='活动描述')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '进行中'), ('ended', '已结束')], default='draft', max_length=10, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('leader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_activities', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
            ],
            options={
                'verbose_name': '义诊活动',
                'verbose_name_plural': '义诊活动列表',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientId', models.PositiveIntegerField(null=True)),
                ('doctorId', models.PositiveIntegerField(null=True)),
                ('patientName', models.CharField(max_length=40, null=True)),
                ('doctorName', models.CharField(max_length=40, null=True)),
                ('appointmentDate', models.DateField(auto_now=True)),
                ('description', models.TextField(max_length=500)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '预约',
                'verbose_name_plural': '预约列表',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(default='', max_length=20, verbose_name='真实姓名')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], default='M', max_length=1, verbose_name='性别')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号')),
                ('workplace', models.CharField(blank=True, max_length=100, verbose_name='执业医院')),
                ('introduction', models.TextField(blank=True, verbose_name='个人简介')),
                ('social_roles', models.TextField(blank=True, verbose_name='社会职务')),
                ('status', models.BooleanField(default=False, verbose_name='审批状态')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic/DoctorProfilePic/', verbose_name='头像')),
                ('address', models.CharField(blank=True, default='', max_length=40)),
                ('department', models.CharField(blank=True, choices=[('Cardiologist', 'Cardiologist'), ('Dermatologists', 'Dermatologists'), ('Emergency Medicine Specialists', 'Emergency Medicine Specialists'), ('Allergists/Immunologists', 'Allergists/Immunologists'), ('Anesthesiologists', 'Anesthesiologists'), ('Colon and Rectal Surgeons', 'Colon and Rectal Surgeons')], default='', max_length=50, verbose_name='科室(旧)')),
            ],
            options={
                'verbose_name': '医生',
                'verbose_name_plural': '医生列表',
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_date', models.DateField(default=datetime.date.today, verbose_name='就诊日期')),
                ('visit_no', models.CharField(blank=True, max_length=20, unique=True, verbose_name='就诊流水号')),
                ('visit_type', models.CharField(choices=[('outpatient', '门诊'), ('charity', '义诊'), ('referral', '转诊')], default='charity', max_length=10, verbose_name='就诊类型')),
                ('chief_complaint', models.TextField(blank=True, verbose_name='主诉')),
                ('present_illness', models.TextField(blank=True, verbose_name='现病史')),
                ('past_history_note', models.TextField(blank=True, verbose_name='既往史备注')),
                ('auxiliary_exam', models.TextField(blank=True, verbose_name='辅助检查')),
                ('treatment_plan', models.TextField(blank=True, verbose_name='治疗计划')),
                ('informed_consent', models.TextField(blank=True, verbose_name='知情同意')),
                ('treatment_record', models.TextField(blank=True, verbose_name='治疗记录')),
                ('followup_notes', models.TextField(blank=True, verbose_name='复诊备注')),
                ('face_symmetry', models.BooleanField(default=True, verbose_name='面部对称')),
                ('has_swelling', models.BooleanField(default=False, verbose_name='是否肿胀')),
                ('mouth_opening', models.CharField(choices=[('normal', '正常'), ('mild_limit', '轻度受限'), ('severe_limit', '重度受限')], default='normal', max_length=15, verbose_name='开口度')),
                ('extraoral_note', models.TextField(blank=True, verbose_name='口外检查备注')),
                ('has_periodontal', models.BooleanField(default=False, verbose_name='牙周问题')),
                ('mucosa_normal', models.BooleanField(default=True, verbose_name='黏膜正常')),
                ('mucosa_note', models.TextField(blank=True, verbose_name='黏膜备注')),
                ('intraoral_note', models.TextField(blank=True, verbose_name='口内检查备注')),
                ('diagnosis', models.TextField(blank=True, verbose_name='综合诊断')),
                ('observations', models.JSONField(default=list, verbose_name='观测数据(HL7 OBX)')),
                ('billing', models.JSONField(blank=True, null=True, verbose_name='费用信息(HL7 FT1)')),
                ('photos', models.JSONField(default=list, verbose_name='口腔照片路径(最多20张)')),
                ('doctor_confirmed', models.BooleanField(default=False, verbose_name='医生已确认')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.activity', verbose_name='所属活动')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_records', to=settings.AUTH_USER_MODEL, verbose_name='诊疗医生')),
            ],
            options={
                'verbose_name': '病历',
                'verbose_name_plural': '病历列表',
            },
        ),
        migrations.CreateModel(
            name='PatientDischargeDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientId', models.PositiveIntegerField(null=True)),
                ('patientName', models.CharField(max_length=40)),
                ('assignedDoctorName', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('symptoms', models.CharField(max_length=100, null=True)),
                ('admitDate', models.DateField()),
                ('releaseDate', models.DateField()),
                ('daySpent', models.PositiveIntegerField()),
                ('roomCharge', models.PositiveIntegerField()),
                ('medicineCost', models.PositiveIntegerField()),
                ('doctorFee', models.PositiveIntegerField()),
                ('OtherCharge', models.PositiveIntegerField()),
                ('total', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': '出院结算',
                'verbose_name_plural': '出院结算列表',
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(max_length=20, verbose_name='真实姓名')),
                ('mobile', models.CharField(max_length=20, verbose_name='手机号')),
                ('status', models.BooleanField(default=False, verbose_name='审批状态')),
                ('joined_date', models.DateField(auto_now_add=True, verbose_name='加入日期')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户账号')),
            ],
            options={
                'verbose_name': '志愿者',
                'verbose_name_plural': '志愿者列表',
            },
        ),
        migrations.CreateModel(
            name='ToothFinding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tooth_number', models.PositiveIntegerField(verbose_name='牙位(FDI编码)')),
                ('finding_type', models.CharField(choices=[('caries', '龋齿'), ('missing', '缺失'), ('filling', '充填'), ('crown', '冠修复'), ('other', '其他')], max_length=10, verbose_name='问题类型')),
                ('note', models.CharField(blank=True, max_length=100, verbose_name='备注')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tooth_findings', to='hospital.medicalrecord', verbose_name='病历')),
            ],
            options={
                'verbose_name': '牙位检查',
                'verbose_name_plural': '牙位检查列表',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='站点名称')),
                ('address', models.CharField(max_length=200, verbose_name='地址')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='纬度')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='经度')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
            ],
            options={
                'verbose_name': '义诊站点',
                'verbose_name_plural': '义诊站点列表',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(default='', max_length=20, verbose_name='真实姓名')),
                ('id_card', models.CharField(blank=True, max_length=18, verbose_name='身份证号')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女'), ('U', '未知')], default='U', max_length=1, verbose_name='性别')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('mobile', models.CharField(blank=True, max_length=20, verbose_name='手机号')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='住址')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='扩展信息(HL7)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('symptoms', models.CharField(blank=True, max_length=100, null=True, verbose_name='症状(旧)')),
                ('assignedDoctorId', models.PositiveIntegerField(blank=True, null=True, verbose_name='分配医生ID(旧)')),
                ('admitDate', models.DateField(auto_now=True, verbose_name='入院日期(旧)')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic/PatientProfilePic/', verbose_name='头像(旧)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_patients', to=settings.AUTH_USER_MODEL, verbose_name='录入人')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户账号')),
            ],
            options={
                'verbose_name': '患者',
                'verbose_name_plural': '患者列表',
            },
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='hospital.patient', verbose_name='患者'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='volunteer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteered_records', to=settings.AUTH_USER_MODEL, verbose_name='接诊志愿者'),
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hypertension', models.BooleanField(default=False, verbose_name='高血压')),
                ('heart_disease', models.BooleanField(default=False, verbose_name='心脏病')),
                ('hyperglycemia', models.BooleanField(default=False, verbose_name='高血糖')),
                ('hypoglycemia', models.BooleanField(default=False, verbose_name='低血糖')),
                ('coagulation', models.BooleanField(default=False, verbose_name='凝血障碍')),
                ('medications', models.TextField(blank=True, verbose_name='用药情况')),
                ('allergies', models.TextField(blank=True, verbose_name='过敏史')),
                ('other_history', models.TextField(blank=True, verbose_name='其他病史')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_history', to='hospital.patient', verbose_name='患者')),
            ],
            options={
                'verbose_name': '既往病史',
                'verbose_name_plural': '既往病史列表',
            },
        ),
        migrations.CreateModel(
            name='DoctorSpecialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(choices=[('restorative', '修复'), ('orthodontics', '正畸'), ('endodontics', '牙体牙髓'), ('implant', '种植'), ('periodontics', '牙周'), ('pediatric', '儿牙'), ('general', '全科')], max_length=20, verbose_name='专科')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_specialties', to='hospital.doctor', verbose_name='医生')),
            ],
            options={
                'verbose_name': '医生专科',
                'verbose_name_plural': '医生专科列表',
            },
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialties',
            field=models.ManyToManyField(blank=True, through='hospital.DoctorSpecialty', to='hospital.doctor'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ActivityParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('doctor', '医生'), ('volunteer', '志愿者')], max_length=10, verbose_name='角色')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.activity', verbose_name='活动')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '活动参与者',
                'verbose_name_plural': '活动参与者列表',
                'unique_together': {('activity', 'user')},
            },
        ),
    ]
