# Generated by Django 4.2.29 on 2026-03-22 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_remove_appointment_doctorid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='assignedDoctorId',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='分配医生ID(旧)'),
        ),
        migrations.AlterUniqueTogether(
            name='doctorspecialty',
            unique_together={('doctor', 'specialty')},
        ),
    ]
